# Speed up?
sudo: true
install: true
language: java
jdk: [oraclejdk8]

before_script:
  - chmod +x gradlew
script: ./gradlew clean build

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
