options:
  auto-update: true
  armor-update-interval: 10
  give-guide-on-first-join: true
  print-out-loading: false
  print-out-github-data-retrieving: false
  enable-armor-effects: true
  prefix: '&a&lSlimefun &7>'
  auto-save-delay-in-minutes: 10
  show-vanilla-recipes-in-guide: true
  allow-free-creative-research: true
  emerald-enchantment-limit: 2
  research-unlock-fireworks: true
  research-give-fireworks: true
  legacy-ore-washer: false
  legacy-dust-washer: false
guide:
  default-view-book: false
URID:
  info-delay: 3000
  custom-ticker-delay: 12
  enable-tickers: true
items:
  talismans: true
  coolers: true
  backpacks: true
research-ranks:
- Chicken
- Cow
- Spider
- Villager
- Beginner
- Clumsy Student
- Unskilled Student
- Incompetent Student
- Student
- Clumsy Apprentice
- Apprentice
- Skilled Apprentice
- Upcoming Mage
- Excellent Mage
- Young Magician
- Incompetent Magician
- Common Magician
- Magician
- Proficient Magician
- Skilled Magician
- Accustomed Magician
- Great Magician
- Clumsy Wizard
- Wizard
- Common Wizard
- Skilled Wizard
- Great Wizard
- Impressive Wizard
- Young Master
- Clumsy Master
- Upcoming Master
- Competent Master
- Master
- Skilled Master
- Excellent Master
- Great Master
- Proficient Master
- The chosen One
