name: Respond to closed Issue
on: 
  issues: 
    types: [closed]

jobs:
  comment:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'Bug Report')
    steps:
      - name: Query recent commits
        uses: TheBusyBiscuit/recently-closed-issues@1.1.0
        id: resolved
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          max_commits: 20
      - name: Add label
        if: contains(${{ steps.commits.outputs.issues }}, ${{ github.event.issue.number }})
        uses: maxkomarychev/octions/octions/issues/add-labels@master
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          issue_number: ${{ github.event.issue.number }}
          labels: 'Resolved'
      - uses: maxkomarychev/octions/octions/issues/create-comment@master
        if: contains(${{ steps.commits.outputs.issues }}, ${{ github.event.issue.number }}) == false
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          issue_number: ${{ github.event.issue.number }}
          body: |-
            Your issue was closed, it may fall under one or more of the following categories.
            **Please wait for an admin to tick off the points that apply.**
            Do not post your Issue again until an Admin has reviewed this message and you fixed the points that were ticked.
            This message can be deleted if your issue was resolved.
            
            Please respond below, if you have any questions.
            
            * [ ] You did not follow our template. Please follow the Issue template to help us identify your issue more quickly.
            * [ ] You did not provide any information about your versions (We absolutely need your exact versions, \"latest\" is not helpful)
            * [ ] You did not provide a proper description to the problem.
            * [ ] We were unable to reproduce issue, if you think your issue still persists then please comment down below and give a better description on how to reproduce it.
            * [ ] Your issue was posted in a foreign language, we only accept english issues on here.
            * [ ] Your issue is not a bug, it is either intended or something we cannot change.
            * [ ] Your issue is not a bug, please only use this issue tracker to report bugs. Any other kind of communication should happen on discord or elsewhere.
            * [ ] Your issue was already reported, it is a duplicate. Check the other open issues first before posting!
            * [ ] You posted an error without using pastebin. Please always post errors via pastebin.
            * [ ] You have posted multiple issues at once. Please post a seperate issue for each bug you encountered.
            * [ ] Your issue has already been fixed in a later version of Slimefun or CS-CoreLib, you should update.
            * [ ] You are using an outdated version of Slimefun / CS-CoreLib, again, you should update.
            * [ ] You are using an unsupported version of Minecraft. We only provide support for the latest version of Minecraft, old versions are not supported anymore.
            * [ ] You are using a \"stable\" version of Slimefun (prefixed with \"RC - \"), your issue may have been fixed in a development build, so we only accept bug reports from those.
            * [ ] You are on the wrong issue tracker. We would like to remind you that this Issue Tracker is **only for Slimefun**. To report bugs on any addons, head to the corresponding issue tracker of that addon.
            
            Make sure to check out our article on [How to report bugs](https://github.com/TheBusyBiscuit/Slimefun4/wiki/How-to-report-bugs) for even more information.
