name: Discord Webhook

on:
  push:
    paths:
    - 'src/**'
    - '!src/main/resources/languages/**'
    - 'pom.xml'

jobs:
  report:

    name: Discord Webhook
    runs-on: ubuntu-latest

    ## Only run this on the main repo
    if: github.repository == 'Slimefun/Slimefun4'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.0.2

    - name: Set up Java JDK 17
      uses: actions/setup-java@v3.4.0
      with:
        distribution: 'adopt'
        java-version: '17'
        java-package: jdk
        architecture: x64

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Run Discord Webhook
      uses: baked-libs/discord-webhook@1.5.1
      with:
        id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
