name: Javadocs Generator

on:
  push:
    branches:
    - master

jobs:
  javadocs:

    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[javadocs]')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Set up JDK 1.9
      uses: giltene/setup-java@master
      with:
        java-version: 9.0.4
    - name: Generate Javadocs
      run: mvn javadoc:javadoc
    - name: Push to repository
      uses: github-actions-x/commit@v2.5
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        push-branch: 'master'
        commit-message: '[CI skip] Updated Javadocs'
        force-add: 'true'
        files: docs
        name: TheBusyBot
        email: ${{ secrets.BOT_EMAIL }}
