name: Pull Request Labels

on:
  pull_request_target:
    types:
      - opened

permissions:
  contents: read
  pull-requests: write

jobs:
  pr-labeler:

    name: Pull Request Labels
    runs-on: ubuntu-latest
    if: github.repository == 'Slimefun/Slimefun4'

    steps:
      - uses: baked-libs/pull-request-labels@v1.1
        id: labeller
        name: Apply labels based on branch
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          renovate: 'ğŸš¨ Dependency Update'
          crowdin: 'ğŸ“„ Translations Update'
          feature: 'ğŸˆ Feature'
          fix: 'âœ¨ Fix'
          chore: 'ğŸ§¹ Chores'
          performance: 'ğŸ’¡ Performance Optimization'
          api: 'ğŸ”§ API'
          compatibility: 'ğŸ¤ Compatibility'

      - uses: thollander/actions-comment-pull-request@v2.5.0
        name: Leave a comment about the applied label
        if: ${{ steps.labeller.outputs.applied != 0 }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Your Pull Request was automatically labelled as: "${{ steps.labeller.outputs.applied }}"
            Thank you for contributing to this project! â¤ï¸

      - uses: thollander/actions-comment-pull-request@v2.5.0
        name: Leave a comment about our branch naming convention
        if: ${{ steps.labeller.outputs.applied == 0 }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            **Pro Tip!**
            You can help us label your Pull Requests by using the following branch naming convention next time you create a pull request. â¤ï¸
            Branch naming convention | Label
            ------------------------ | ------
            `feature/**`             | ğŸˆ Feature
            `fix/**`                 | âœ¨ Fix
            `chore/**`               | ğŸ§¹ Chores
            `api/**`                 | ğŸ”§ API
            `performance/**`         | ğŸ’¡ Performance Optimization
            `compatibility/**`       | ğŸ¤ Compatibility
            <hr>
            If your changes do not fall into any of these categories, don't worry.
            You can just ignore this message in that case! ğŸ‘€
