name: PR Labeler
on:
  pull_request:
    types: [opened]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: WalshyDev/pr-labels@v1
        with:
          token: "${{ secrets.ACCESS_TOKEN }}"
          feature: 'New Feature'
          fix: 'ğŸ Bug Fix'
          chore: 'Chore'
          perf: 'ğŸ› ï¸ Performance Improvement'
          performance: 'ğŸ› ï¸ Performance Improvement'
