name: Translation Notifier
on: 
  push:
    branches:
    - master
    paths:
    - 'src/main/resources/languages/**_en.yml'
    
jobs:
  notify:
    name: Translation-Notifier
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification
        uses: Ilshidur/action-discord@master
        with:
          args: '<@&665202905271369776> Slimefun4''s language files have been updated! https://gitlocalize.com/repo/3841'
        env:
          DISCORD_WEBHOOK: ${{ secrets.TRANSLATOR_WEBHOOK }}
